---
- name: check distribute
  fail: msg='this tasks support for CentOS 6.x only. Your distribution is {{ ansible_distribution }} {{ ansible_distribution_version }}'
  when: ansible_distribution_version|truncate(1, True, '') != '6'
- name: install java
  yum: name={{ java_package | default('java-1.7.0-openjdk.x86_64') }} state=present
- name: put yum.repo
  copy: src=etc/yum.repos.d/elasticsearch-1.3.repo dest=/etc/yum.repos.d/elasticsearch-1.3.repo
- name: install Elasticsearch
  yum: name=elasticsearch state=present
- name: chkconfig on
  command: chkconfig elasticsearch on
- name: is head plugin installed?
  shell: bin/plugin --list | grep '\- {{ elasticsearch_plugin_head_name }}' chdir={{ elasticsearch_home_dir }}
  register: is_head_plugin_installed
  ignore_errors: True
- name: install head plugin
  shell: bin/plugin --install {{ elasticsearch_plugin_head_path }} chdir={{ elasticsearch_home_dir }}
  when: is_head_plugin_installed is defined and is_head_plugin_installed.rc != 0
- name: is kuromoji plugin installed?
  shell: bin/plugin --list | grep '\- {{ elasticsearch_plugin_analysis_kuromoji_name }}' chdir={{ elasticsearch_home_dir }}
  register: is_kuromoji_plugin_installed
  ignore_errors: True
- name: install kuromoji plugin
  shell: bin/plugin --install {{ elasticsearch_plugin_analysis_kuromoji_path }} chdir={{ elasticsearch_home_dir }}
  when: is_kuromoji_plugin_installed is defined and is_kuromoji_plugin_installed.rc != 0
- name: elasticsearch start
  service: name=elasticsearch state=started
